name: Build

on:
  schedule:
  - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ipdata
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Install utils
        run: sudo apt-get update && sudo apt-get -y --no-install-recommends install jq postgresql-client

      - name: Run our scripts
        id: release
        run: |
          ./1-gen-blocked-ips.sh
          ./2-gen-allowed-ips.sh
          ./3-gen-public-cloud-ranges.sh
          ./4-gen-user-agents.sh
          ./5-gen-cdn-ips.sh
          ./6-get-geo-ranges.sh
          echo "builddate=$(date -Is)" >> $GITHUB_OUTPUT
          echo "epochdate=$(date +%s)" >> $GITHUB_OUTPUT

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: SiteHost NZ
          author_email: support@sitehost.co.nz
          message: "Automatic build date: ${{ steps.release.outputs.builddate }}"
          tag: "${{ steps.release.outputs.epochdate }}"
